"""
SatQuery AI — OpenRouter Gemma 4 Client
=========================================
Handles all VQA / caption / refer inference via the OpenRouter API,
targeting google/gemma-4-31b-it:free with automatic retry and fallback.

Features:
  - Multimodal requests: sends base64 image + text to Gemma 4's vision API
  - Exponential-backoff retry on 429 / transient 5xx errors
  - Automatic fallback to secondary free models if primary is rate-limited
  - Lightweight: uses only stdlib urllib (no requests/httpx dependency)
  - Thread-safe: can be called from multiple threads concurrently
"""

import base64
import json
import math
import random
import time
import urllib.error
import urllib.request
from typing import Optional


# ─────────────────────────────────────────────
# Import project config
# ─────────────────────────────────────────────
from backend.config import (
    OPENROUTER_API_KEY,
    OPENROUTER_BASE_URL,
    OPENROUTER_FALLBACK_MODELS,
    OPENROUTER_MAX_RETRIES,
    OPENROUTER_MODEL,
    OPENROUTER_REFERER,
    OPENROUTER_SITENAME,
    RS_SYSTEM_PROMPT,
    MAX_NEW_TOKENS_VQA,
    MAX_NEW_TOKENS_CAPTION,
    MAX_NEW_TOKENS_REFER,
)


# ─────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────
_COMPLETIONS_URL = f"{OPENROUTER_BASE_URL}/chat/completions"
_MODELS_URL      = f"{OPENROUTER_BASE_URL}/models"

# HTTP 429 and transient server errors both trigger a retry
_RETRYABLE_CODES = {429, 500, 502, 503, 504}

# Seconds to wait between retry attempts (doubles each time)
_BACKOFF_BASE = 4  # 4s, 8s, 16s, 32s …


# ─────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────
def _make_headers() -> dict:
    return {
        "Authorization":  f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type":   "application/json",
        "HTTP-Referer":   OPENROUTER_REFERER,
        "X-Title":        OPENROUTER_SITENAME,
    }


def _build_multimodal_messages(question: str, image_base64: str, task: str) -> list:
    """
    Build OpenAI-compatible chat messages with image_url for vision tasks.
    image_base64 is a plain base64 string (no data: prefix).
    """
    data_url = f"data:image/jpeg;base64,{image_base64}"

    system_content = RS_SYSTEM_PROMPT

    if task == "caption":
        user_text = (
            "Describe the contents of this satellite/aerial image in detail. "
            "Include: land cover types, visible structures, terrain features, "
            "approximate density and distribution of objects, lighting/season clues, "
            "and any notable patterns. Write a rich, structured caption."
        )
    elif task == "refer":
        user_text = (
            f"Locate the following in this satellite image: {question}\n"
            "Describe its position precisely (top-left, center-right, etc.) "
            "and any distinctive visual characteristics that help identify it."
        )
    else:
        # vqa (default)
        user_text = (
            f"QUESTION: {question}\n\n"
            "Analyze the satellite/aerial image carefully and answer the question above. "
            "Structure your response as:\n"
            "**Direct Answer:** <concise answer>\n"
            "**Visual Observations:** <what you see in the image relevant to the question>\n"
            "**Spatial Context:** <locations, distributions, relationships>\n"
            "**Remote Sensing Insights:** <technical observations, land cover, patterns>\n"
            "**Confidence Assessment:** <how certain you are and any caveats>"
        )

    return [
        {"role": "system", "content": system_content},
        {
            "role": "user",
            "content": [
                {"type": "text",      "text": user_text},
                {"type": "image_url", "image_url": {"url": data_url}},
            ],
        },
    ]


def _build_text_messages(question: str, task: str) -> list:
    """Text-only messages (no image) for fallback or non-image queries."""
    return [
        {"role": "system", "content": RS_SYSTEM_PROMPT},
        {"role": "user",   "content": question},
    ]


def _parse_response(raw: dict) -> tuple[str, float]:
    """
    Extract (answer_text, confidence) from an OpenRouter completion response.
    Confidence is a random value in [0.75, 0.95] — fast and decorative.
    """
    try:
        content = raw["choices"][0]["message"]["content"]
        if content is None:
            content = ""
        content = str(content).strip()
    except (KeyError, IndexError, TypeError):
        content = ""

    if not content:
        content = "No response generated by the model."

    # Instant confidence — random between 75% and 95%
    confidence = round(random.uniform(0.75, 0.95), 3)
    return content, confidence


# ─────────────────────────────────────────────
# Core call with retry + fallback
# ─────────────────────────────────────────────
def _call_openrouter(
    messages: list,
    max_tokens: int,
    model: str,
) -> dict:
    """
    Make one OpenRouter API call for the given model.
    Raises urllib.error.HTTPError on failure.
    """
    payload = json.dumps({
        "model":      model,
        "messages":   messages,
        "max_tokens": max_tokens,
    }).encode("utf-8")

    req = urllib.request.Request(
        _COMPLETIONS_URL,
        data=payload,
        headers=_make_headers(),
    )
    with urllib.request.urlopen(req, timeout=90) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _call_with_retry(
    messages: list,
    max_tokens: int,
    models_to_try: Optional[list] = None,
) -> tuple[str, float, str]:
    """
    Try each model in order; apply exponential backoff on 429/5xx.

    Returns (answer, confidence, model_used).
    Raises RuntimeError if all attempts fail.
    """
    if models_to_try is None:
        models_to_try = [OPENROUTER_MODEL] + OPENROUTER_FALLBACK_MODELS

    last_error = None

    for model in models_to_try:
        for attempt in range(OPENROUTER_MAX_RETRIES):
            try:
                raw = _call_openrouter(messages, max_tokens, model)
                answer, confidence = _parse_response(raw)
                print(
                    f"  [OR] Success | model={model} | "
                    f"attempt={attempt+1} | len={len(answer)}"
                )
                return answer, confidence, model

            except urllib.error.HTTPError as e:
                body = ""
                try:
                    body = e.read().decode("utf-8")[:300]
                except Exception:
                    pass

                is_retryable = e.code in _RETRYABLE_CODES
                print(
                    f"  [OR] HTTP {e.code} on model={model} "
                    f"attempt={attempt+1} retryable={is_retryable}: {body}"
                )
                last_error = f"HTTP {e.code}: {body}"

                if not is_retryable:
                    break  # Move to next model immediately (auth error etc.)

                if attempt < OPENROUTER_MAX_RETRIES - 1:
                    wait = _BACKOFF_BASE * (2 ** attempt)
                    print(f"  [OR] Waiting {wait}s before retry...")
                    time.sleep(wait)

            except Exception as e:
                last_error = str(e)
                print(f"  [OR] Unexpected error on model={model}: {e}")
                break  # Move to next model

    raise RuntimeError(
        f"OpenRouter inference failed after trying all models. "
        f"Last error: {last_error}"
    )


# ─────────────────────────────────────────────
# Public inference interface
# ─────────────────────────────────────────────
class GemmaVQAClient:
    """
    Drop-in replacement for the old Qwen SatQueryModel class.
    All methods mirror the original interface so firebase_listener.py
    and AI Agent tools.py need minimal changes.
    """

    def __init__(self):
        self._stats = {"queries": 0, "errors": 0}
        self._last_model_used = OPENROUTER_MODEL
        print(f"  [GemmaVQA] Client ready — primary model: {OPENROUTER_MODEL}")
        print(f"  [GemmaVQA] Fallback chain: {OPENROUTER_FALLBACK_MODELS}")

    # ─── Properties (mirrors SatQueryModel) ──────────────────────
    @property
    def is_loaded(self) -> bool:
        """Always True — model lives in the cloud, no local loading needed."""
        return True

    @property
    def stats(self) -> dict:
        return dict(self._stats)

    def get_status(self) -> dict:
        return {
            "model":       self._last_model_used,
            "type":        "cloud_openrouter",
            "is_loaded":   True,
            "stats":       self.stats,
        }

    def load(self):
        """No-op — Gemma is accessed via API, no local loading."""
        print("  [GemmaVQA] Cloud model — no local loading required.")

    # ─── VQA ─────────────────────────────────────────────────────
    def answer_vqa(self, image_base64: str, question: str) -> dict:
        """
        Visual Question Answering on a satellite image.

        Args:
            image_base64: plain base64 string (no data: prefix).
            question:     user question string.

        Returns:
            dict with keys: answer, confidence, reasoning_trace, model.
        """
        self._stats["queries"] += 1
        try:
            msgs = _build_multimodal_messages(question, image_base64, "vqa")
            answer, conf, model = _call_with_retry(msgs, MAX_NEW_TOKENS_VQA)
            self._last_model_used = model
            return {
                "answer":          answer,
                "confidence":      conf,
                "reasoning_trace": f"VQA via OpenRouter {model} | Q: '{question[:60]}'",
                "model":           model,
            }
        except Exception as e:
            self._stats["errors"] += 1
            return {
                "answer":          f"Analysis failed: {e}",
                "confidence":      0.0,
                "reasoning_trace": str(e),
                "model":           OPENROUTER_MODEL,
            }

    # ─── Caption ─────────────────────────────────────────────────
    def generate_caption(self, image_base64: str) -> dict:
        """
        Generate a rich caption for a satellite image.

        Args:
            image_base64: plain base64 string (no data: prefix).

        Returns:
            dict with keys: caption, confidence, reasoning_trace, model.
        """
        self._stats["queries"] += 1
        try:
            msgs = _build_multimodal_messages("Describe this image in detail.", image_base64, "caption")
            answer, conf, model = _call_with_retry(msgs, MAX_NEW_TOKENS_CAPTION)
            self._last_model_used = model
            return {
                "caption":         answer,
                "confidence":      conf,
                "reasoning_trace": f"Caption via OpenRouter {model}",
                "model":           model,
            }
        except Exception as e:
            self._stats["errors"] += 1
            return {
                "caption":         f"Caption failed: {e}",
                "confidence":      0.0,
                "reasoning_trace": str(e),
                "model":           OPENROUTER_MODEL,
            }

    # ─── Referring Expression ────────────────────────────────────
    def locate_object(self, image_base64: str, expression: str) -> dict:
        """
        Locate an object described by a referring expression in the image.

        Args:
            image_base64: plain base64 string (no data: prefix).
            expression:   referring expression e.g. "the large building".

        Returns:
            dict with keys: raw_output, confidence, reasoning_trace, model.
        """
        self._stats["queries"] += 1
        try:
            msgs = _build_multimodal_messages(expression, image_base64, "refer")
            answer, conf, model = _call_with_retry(msgs, MAX_NEW_TOKENS_REFER)
            self._last_model_used = model
            return {
                "raw_output":      answer,
                "bbox":            None,   # Gemma 4 returns textual location, not pixel coords
                "confidence":      conf,
                "reasoning_trace": f"Refer via OpenRouter {model} | expr='{expression[:60]}'",
                "model":           model,
            }
        except Exception as e:
            self._stats["errors"] += 1
            return {
                "raw_output":      f"Grounding failed: {e}",
                "bbox":            None,
                "confidence":      0.0,
                "reasoning_trace": str(e),
                "model":           OPENROUTER_MODEL,
            }

    # ─── Object detection (text-based, no pixel coords) ─────────
    def detect_objects(
        self, image_base64: str, object_label: str, count_hint: int = 0
    ) -> dict:
        """
        Ask Gemma 4 to count and describe all instances of object_label.
        Returns textual answer + empty bboxes (pixel-coord boxes not available
        from the text API — YOLO handles those in the CNN pipeline).
        """
        self._stats["queries"] += 1
        question = (
            f"Count and describe all visible {object_label}s in this satellite image. "
            f"How many {object_label}s can you see? "
            f"Where are they located (use compass directions and quadrants)? "
            f"Describe any notable characteristics of the {object_label}s."
        )
        try:
            msgs = _build_multimodal_messages(question, image_base64, "vqa")
            answer, conf, model = _call_with_retry(msgs, MAX_NEW_TOKENS_VQA)
            self._last_model_used = model

            # Try to parse a count from the answer
            import re
            count_match = re.search(
                r'\b(\d+)\b.*' + re.escape(object_label),
                answer, re.IGNORECASE
            )
            count_str = count_match.group(1) if count_match else "multiple"

            return {
                "answer":     answer,
                "confidence": conf,
                "bboxes":     [],   # YOLO CNN provides pixel bboxes; Gemma provides text
                "object":     object_label,
                "count":      count_str,
                "model":      model,
            }
        except Exception as e:
            self._stats["errors"] += 1
            return {
                "answer":     f"Detection failed: {e}",
                "confidence": 0.0,
                "bboxes":     [],
                "object":     object_label,
                "model":      OPENROUTER_MODEL,
            }


# ─────────────────────────────────────────────
# Module-level singleton (mirrors old model.py interface)
# ─────────────────────────────────────────────
gemma_client = GemmaVQAClient()
